# Generated by Django 3.1 on 2021-08-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variations',
        ),
    ]
